### PR TITLE
fix deadlock  #57

### LINKED ISSUE #57: deadlock in Close
### Problem

Whenever eviction and close run at the same time. There is a possible deadlock because of the closeLock mutex usage on poo.go:487. We can unlock it whenever we don't need it rather than using defer.

### Repreduce UT
```go
func (suit *PoolTestSuite) TestConcurrentCloseAndEvict() {
	ctx := context.Background()
	suit.pool.Config.MinIdle = 1
	suit.pool.Config.SoftMinEvictableIdleTime = time.Millisecond * 100
	suit.pool.Config.TimeBetweenEvictionRuns = time.Millisecond * 500
	suit.factory.destroyLatency = time.Millisecond * 1000 // Destroy takes 1000 ms
	suit.pool.PreparePool(ctx)
	suit.pool.StartEvictor()
	suit.Equal(1, suit.pool.GetNumIdle())
	ticker := time.NewTicker(time.Millisecond * 1000)
	testTimeoutTicker := time.NewTicker(time.Millisecond * 5000) // if time exceeds test fails
	go func() {
		select {
		case <-testTimeoutTicker.C:
			// Time-out
			suit.FailNow("Time is exceeds on pool close")
		}
	}()
	select {
	case <-ticker.C:
		suit.pool.Close(ctx)
	}
}
```

### PR DESCRIPTION
**Pull request by ykalayy**
Fix #57 
1. closed state access and updates are wrapped with get/set functions. To eliminate possible deadlocks on pool close

### CODE REVIEW

**Comment by ykalayy** [comment]
@jolestar Could you please review?

**Review by jolestar — APPROVED** [review]
LGTM, thanks

**Comment by ykalayy** [comment]
@jolestar I forget to stop testTimeoutTicker in UT. and Ofc, It is affected other tests. I updated. 
Added:
```go
defer testTimeoutTicker.Stop()
```

Could you review it again, please?

**Comment by ykalayy** [comment]
Added ticker stop in UT:
```go
defer ticker.Stop()
```

**Comment by ykalayy** [comment]
Added ticker stop in UT:
```go
defer ticker.Stop()
```

**Pull request merged**
